language: node_js

node_js: 10

cache:
  yarn: true
  directories:
    - "node_modules"

# configuration
install: 
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc  
  - git config user.email "davidmortonmail@gmail.com"
  - git config user.name "daithimorton"
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/daithimorton/bowhead.git

stages:
  - build
  - test
  - publish

jobs:  
  include:
    - stage: build
      script:
        - yarn build:cra-template-bowhead
      after_success:
        - git status
        - git stash
        - git checkout master
        - git stash pop
        - git add .
        - git commit -m "chore(*) TravisCI update [skip ci]"
        - git push origin HEAD:master
    - stage: test
      node_js: 10
      script: echo 'test'
    - stage: test
      node_js: 12
      script: echo 'test'
    - stage: publish
      deploy:
        - provider: script
          script: yarn release
          cleanup: false
          on:
            branch: master