language: node_js

node_js:
  - '12'

script:
  - echo 'test'

after_success:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote add -f publish https://${GITHUB_TOKEN}@github.com:daithimorton/bowhead.git
  - git checkout master

deploy:
  - provider: script
    script: yarn release
    skip_cleanup: true
    keep_history: true
    on:
      branch: master