language: node_js

node_js:
  - '10'
  - '12'

cache:
  yarn: true
  directories:
    - "node_modules"

# configuration
install: 
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc  
  - git config user.email "davidmortonmail@gmail.com"
  - git config user.name "daithimorton"
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/daithimorton/bowhead.git

# build
script:
  - yarn build:cra-template-bowhead

# build succeeded
after_success:
  # commit any changes made to the template directory
  - git stash
  - git checkout master
  - git stash pop
  - git add .
  - git commit -m "chore(*) TravisCI update [skip ci]"
  - git push origin HEAD:master 

# publish to NPM
deploy:
  - provider: script
    script: yarn release
    skip_cleanup: true
    on:
      branch: master