language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - "node_modules"

stages:  
  - test
  - name: publish
    if: branch = master

jobs:
  include: 
    - stage: test
      script:
        - yarn lint
        - yarn build
        - yarn test
    - stage: publish
      before_script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc  
        - git config user.email "davidmortonmail@gmail.com"
        - git config user.name "daithimorton"
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/daithimorton/bowhead.git        
      deploy:
        - provider: script
          script: yarn release        
          on:
            branch: master