language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - "node_modules"

stages:  
  - test
  - name: publish:npm
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include: 
    - stage: test
      script:
        - yarn test # unit/integration
        - yarn test:user # user environment test
    - stage: publish:npm
      before_script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc  
        - git config user.email "davidmortonmail@gmail.com"
        - git config user.name "daithimorton"
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/daithimorton/bowhead.git
        - git fetch origin master
        - git checkout master
      script:
        - yarn release
    - stage: deploy
      script:
        - yarn build
        - yarn deploy